Repository salmorejo-hub-1/uvlhub, pull requests merged in 2024-12, with the labels that each got.

#76 fix: Add external modules to the test workflow Refs: #68
  .github/workflows/tests.yml
  migrations/versions/c0049aaef0e6_.py
Labels: deployment, integration

#77 fix: Add new environment variable to the testing workflow Ref: #68
  .github/workflows/tests.yml
Labels: deployment, integration

#94 fix/WI1.6 Add empty list validation in datasets command Closes #93
  discordbot/src/commands/dataset_commands.py
Labels: incidence, priority:medium

#99 fix/WI1.6 Fixes tests after selenium and implements additional tests Closes #93 #97
  app/modules/auth/seeders.py
  discordbot/src/commands/token_commands.py
  discordbot/tests/test_dataset_commands.py
Labels: enhancement, priority:medium
